AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Expense Tracker Serverless Application

Parameters:
  FrontendCallbackUrl:
    Type: String
    Default: "https://d84l1y8p4kdic.cloudfront.net/callback" # replace with your actual domain url
    Description: "Frontend callback URL for Cognito Hosted UI"
  FrontendLogoutURLs:
    Type: String
    Default: "https://d84l1y8p4kdic.cloudfront.net/logout" # replace with your actual domain url
    Description: "Frontend Logout URL for Cognito Hosted UI"
  Environment:
    Type: String
    AllowedValues:
      - dev
      - staging
      - production
    Default: staging

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12

Resources:
  
  # Cognito User Pool
  ExpenseTrackerUserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: !Sub "UserPool-${Environment}-${AWS::StackName}"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
        - Name: name
          AttributeDataType: String
          Required: true
          Mutable: false
  
  ExpenseTrackerCognitoDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "user-pool-domain-${Environment}-${AWS::StackName}"
      UserPoolId: !Ref ExpenseTrackerUserPool

  ExpenseTrackerUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "UserPoolClient-${Environment}-${AWS::StackName}"
      UserPoolId: !Ref ExpenseTrackerUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        # - https://localhost:3000/callback   # replace with actual domain url
        - !Ref FrontendCallbackUrl
      LogoutURLs:
        # - https://localhost:3000/logout     # replace with actual domain url
        - !Ref FrontendLogoutURLs

  # Cognito Groups
  ExpenseTrackerUserPoolAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: admin
      UserPoolId: !Ref ExpenseTrackerUserPool

  ExpenseTrackerUserPoolUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: user
      UserPoolId: !Ref ExpenseTrackerUserPool

  # Api Gateway
  ExpenseTrackerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod # make this dynamic environment
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt ExpenseTrackerUserPool.Arn
            Identity:
              Header: Authorization
              ValidationExpression: '^Bearer [-0-9a-zA-Z\\.]*$'
  
  # API Key
  ExpenseTrackerApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "ApiKey-${Environment}-${AWS::StackName}"
      Enabled: true
  
  # API Usage Plan
  ExpenseTrackerApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub "UsagePlan-${Environment}-${AWS::StackName}"
      Description: Usage plan to limit API requests
      Throttle:
        RateLimit: 5      # requests per second
        BurstLimit: 10
  
  # Api Usage Plan sudo Key
  ExpenseTrackerApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ExpenseTrackerApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ExpenseTrackerApiUsagePlan

  # DynamoDB Table
  # ExpensesTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: !Sub "ExpensesTable-${Environment}-${AWS::StackName}"
  #     AttributeDefinitions:
  #       - AttributeName: expense_id
  #         AttributeType: S
  #       - AttributeName: user_id
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: user_id
  #         KeyType: HASH
  #       - AttributeName: expense_id
  #         KeyType: RANGE
  #     BillingMode: PAY_PER_REQUEST
  #     StreamSpecification:
  #       StreamViewType: NEW_AND_OLD_IMAGES

  # # Lambda Function: Expenses CRUD
  # ExpensesFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     # CodeUri: ../src/                  # temporarily disabled
  #     Handler: expenses.lambda_handler
  #     Environment:
  #       Variables:
  #         TABLE_NAME: !Ref ExpensesTable
  #     Policies:
  #       - DynamoDBCrudPolicy:
  #           TableName: !Ref ExpensesTable
  #       - Version: '2012-10-17'
  #         Statement:
  #           - Effect: Allow
  #             Action:
  #               - logs:CreateLogStream
  #               - logs:PutLogEvents
  #             Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-ExpensesFunction:*'
  #     Events:
  #       GetExpenses:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref ExpenseTrackerApi
  #           Path: /expenses
  #           Method: GET
  #       CreateExpense:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref ExpenseTrackerApi
  #           Path: /expenses
  #           Method: POST
  #       UpdateExpense:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref ExpenseTrackerApi
  #           Path: /expenses/{id}
  #           Method: PUT
  #       DeleteExpense:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref ExpenseTrackerApi
  #           Path: /expenses/{id}
  #           Method: DELETE

  # Lambda Function: User Registration API
  UserRegistrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: registration.lambda_handler  # Adjust handler as per your code
      # Runtime: python3.12
      # CodeUri: ../src/
      Environment:
        Variables:
          USER_POOL_ID: !Ref ExpenseTrackerUserPool
          CLIENT_ID: !Ref ExpenseTrackerUserPoolClient
      Policies:
        # - AmazonCognitoPowerUserPolicy
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:SignUp
              Resource: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${ExpenseTrackerUserPool}'
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-UserRegistrationFunction:*'
      Events:
        RegisterUser:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseTrackerApi
            Path: /user-registration
            Method: POST
  
  # Lambda Function: User Login API
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/auth/
      Handler: login.handler
      # Runtime: python3.12
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
          - Effect: Allow
            Action:
              - cognito-idp:InitiateAuth
            Resource: "*"  # later narrow to specific UserPool client ARN
      Events:
        ApiLogin:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
      Environment:
        Variables:
          COGNITO_CLIENT_ID: !Ref ExpenseTrackerUserPoolClient
          # AWS_REGION: !Ref AWS::Region

Outputs:

  ApiUrl:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ExpenseTrackerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref ExpenseTrackerUserPool
  
  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref ExpenseTrackerUserPoolClient

  CognitoHostedUI:
    Description: "Cognito Hosted UI URL"
    Value: !Sub "https://${ExpenseTrackerCognitoDomain}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${ExpenseTrackerUserPoolClient}&response_type=code&scope=email+openid+profile&redirect_uri=${FrontendCallbackUrl}"

  LoginApiUrl:
    Description: Login API endpoint URL
    Value: !Sub "https://${ExpenseTrackerApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/auth/login"



