AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Expense Tracker Serverless Application

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12

Resources:
  
  # Cognito User Pool
  ExpenseTrackerUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ExpenseTrackerUserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
        - Name: name
          AttributeDataType: String
          Required: true
          Mutable: false
  
  ExpenseTrackerCognitoDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: expense-tracker-domain # This must be unique in your AWS region
      UserPoolId: !Ref ExpenseTrackerUserPool

  ExpenseTrackerUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ExpenseTrackerClient
      UserPoolId: !Ref ExpenseTrackerUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        # - https://localhost:3000/callback   # replace with actual domain url
        - https://d84l1y8p4kdic.cloudfront.net # replace with your actual domain url
      LogoutURLs:
        # - https://localhost:3000/logout     # replace with actual domain url
        - https://d84l1y8p4kdic.cloudfront.net # replace with your actual domain url

  # Cognito Groups
  ExpenseTrackerUserPoolAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: admin
      UserPoolId: !Ref ExpenseTrackerUserPool

  ExpenseTrackerUserPoolUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: user
      UserPoolId: !Ref ExpenseTrackerUserPool

  # Api Gateway
  ExpenseTrackerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt ExpenseTrackerUserPool.Arn
            Identity:
              Header: Authorization
              ValidationExpression: '^Bearer [-0-9a-zA-Z\\.]*$'

  
  # DynamoDB Table
  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ExpensesTable
      AttributeDefinitions:
        - AttributeName: expense_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: expense_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # Lambda Function: Expenses CRUD
  ExpensesFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri: ../src/                  # temporarily disabled
      Handler: expenses.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpensesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpensesTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-ExpensesFunction:*'
      Events:
        GetExpenses:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseTrackerApi
            Path: /expenses
            Method: GET
        CreateExpense:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseTrackerApi
            Path: /expenses
            Method: POST
        UpdateExpense:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseTrackerApi
            Path: /expenses/{id}
            Method: PUT
        DeleteExpense:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseTrackerApi
            Path: /expenses/{id}
            Method: DELETE
  
Outputs:

  ApiUrl:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ExpenseTrackerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref ExpenseTrackerUserPool
  
  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref ExpenseTrackerUserPoolClient

  CognitoHostedUI:
    Description: "Cognito Hosted UI URL"
    Value: !Sub "https://${ExpenseTrackerCognitoDomain}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${ExpenseTrackerUserPoolClient}&response_type=code&scope=email+openid+profile&redirect_uri=https://localhost:3000/callback"
