AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Expense Tracker Serverless Application

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12

Resources:
  
  # Cognito User Pool
  ExpenseTrackerUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ExpenseTrackerUserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
  
  ExpenseTrackerCognitoDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: expense-tracker-domain # This must be unique in your AWS region
      UserPoolId: !Ref ExpenseTrackerUserPool

  ExpenseTrackerUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ExpenseTrackerClient
      UserPoolId: !Ref ExpenseTrackerUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        # - https://localhost:3000/callback   # replace with actual domain url
        - https://d84l1y8p4kdic.cloudfront.net # replace with your actual domain url
      LogoutURLs:
        # - https://localhost:3000/logout     # replace with actual domain url
        - https://d84l1y8p4kdic.cloudfront.net # replace with your actual domain url

  # Cognito Groups
  ExpenseTrackerUserPoolAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: admin
      UserPoolId: !Ref ExpenseTrackerUserPool

  ExpenseTrackerUserPoolUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: user
      UserPoolId: !Ref ExpenseTrackerUserPool
  
Outputs:
  
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref ExpenseTrackerUserPool
  
  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref ExpenseTrackerUserPoolClient

  CognitoHostedUI:
    Description: "Cognito Hosted UI URL"
    Value: !Sub "https://${ExpenseTrackerCognitoDomain}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${ExpenseTrackerUserPoolClient}&response_type=code&scope=email+openid+profile&redirect_uri=https://localhost:3000/callback"
