name: CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # - name: Run Flake8
      #   run: flake8 . --count --show-source --statistics

      # - name: Run Tests
      #   run: pytest tests/

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-south-1

      # - name: Build SAM Application
      #   run: sam build

      # - name: Deploy with SAM
      #   run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name expense-tracker-dev --capabilities CAPABILITY_IAM
